# Generated by Django 5.2.1 on 2025-06-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('serial_number', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop/Charger', 'Laptop/Charger'), ('Monitor', 'Monitor'), ('Screen', 'Screen'), ('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('Headset', 'Headset'), ('Phone', 'Phone'), ('Remarkable', 'Remarkable'), ('iPad', 'iPad'), ('Printer', 'Printer'), ('Other Devices', 'Other Devices')], max_length=50)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(default='UAE-IT', max_length=100)),
                ('region', models.CharField(default='AE', max_length=10)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=1000, null=True)),
                ('data_sheet_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('image', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
