# Generated by Django 5.2.1 on 2025-06-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name', 'department'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='data_sheet_link',
        ),
        migrations.RemoveField(
            model_name='device',
            name='image',
        ),
        migrations.RemoveField(
            model_name='device',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='website',
        ),
        migrations.AddField(
            model_name='device',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='design',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='headset_sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Headset Serial Number'),
        ),
        migrations.AddField(
            model_name='device',
            name='keyboard_sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Keyboard Serial Number'),
        ),
        migrations.AddField(
            model_name='device',
            name='laptop_sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Laptop Serial Number'),
        ),
        migrations.AddField(
            model_name='device',
            name='monitor_sn_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Monitor SN -1'),
        ),
        migrations.AddField(
            model_name='device',
            name='monitor_sn_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Monitor SN -2'),
        ),
        migrations.AddField(
            model_name='device',
            name='mouse_1_sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mouse-1 Serial Number'),
        ),
        migrations.AddField(
            model_name='device',
            name='mouse_2_sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mouse-2 Serial Number'),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='room_number',
            field=models.CharField(blank=True, choices=[('101', '101'), ('205', '205'), ('501', '501')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='smart_phone_1_sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Smart Phone -1 Serial Number'),
        ),
        migrations.AddField(
            model_name='device',
            name='smart_phone_2_sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Smart Phone -2 Serial Number'),
        ),
    ]
