# Generated by Django 5.2.1 on 2025-06-09 07:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_alter_device_options_remove_device_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('status', models.IntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('status', models.IntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
        migrations.RenameField(
            model_name='device',
            old_name='remarks',
            new_name='remark',
        ),
        migrations.RemoveField(
            model_name='device',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='device',
            name='category',
        ),
        migrations.RemoveField(
            model_name='device',
            name='code',
        ),
        migrations.RemoveField(
            model_name='device',
            name='department',
        ),
        migrations.RemoveField(
            model_name='device',
            name='design',
        ),
        migrations.RemoveField(
            model_name='device',
            name='headset_sn',
        ),
        migrations.RemoveField(
            model_name='device',
            name='keyboard_sn',
        ),
        migrations.RemoveField(
            model_name='device',
            name='laptop_sn',
        ),
        migrations.RemoveField(
            model_name='device',
            name='model',
        ),
        migrations.RemoveField(
            model_name='device',
            name='monitor_sn_1',
        ),
        migrations.RemoveField(
            model_name='device',
            name='monitor_sn_2',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mouse_1_sn',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mouse_2_sn',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='region',
        ),
        migrations.RemoveField(
            model_name='device',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='device',
            name='smart_phone_1_sn',
        ),
        migrations.RemoveField(
            model_name='device',
            name='smart_phone_2_sn',
        ),
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.AddField(
            model_name='device',
            name='date_assigned',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.devicetype'),
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100)),
                ('firstname', models.TextField()),
                ('middlename', models.TextField(blank=True, null=True)),
                ('lastname', models.TextField()),
                ('gender', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('email', models.TextField()),
                ('status', models.IntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.department')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.position')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory_app.employees'),
        ),
    ]
