# Generated by Django 5.2.1 on 2025-06-09 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_department_devicetype_position_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory_app.employees'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.devicetype'),
        ),
    ]
