# Generated by Django 5.2.1 on 2025-06-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_alter_department_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-date_updated', 'serial_number'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterField(
            model_name='device',
            name='date_assigned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
